"""Terminal GitHub Pages site: the page must not be able to lie.

The site is generated, not written: ``docs/assets/data.js`` is emitted from the
repository's own artefacts.  These tests pin the two ways that could go quiet:

* the payload drifts from the figures / reports it claims to describe;
* the page starts depending on something outside the published folder, so it
  renders locally and breaks once GitHub Pages serves it.

They also pin the accessibility hooks that make the terminal usable without a
mouse (a real input element, an aria-live log, a noscript summary).
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS = REPO_ROOT / "docs"
ASSETS = DOCS / "assets"
DATA_JS = ASSETS / "data.js"
FIGURE_DIR = ASSETS / "figures"
REPO_FIGURES = REPO_ROOT / "outputs" / "figures"

GENERATOR = REPO_ROOT / "scripts" / "build_terminal_site.py"
PRELUDE = "window.HB = "

#: The regions of docs/index.html that the builder owns.  Each is delimited by a
#: BEGIN/END marker comment pair and re-rendered from the payload on every
#: build, so a hand edit or a stale number cannot survive --check.
MANAGED_BLOCKS = ("static-meta", "static-fallbacks", "brief-counts",
                  "brief-links", "argument-timeline")


def _load_generator():
    """Import the builder by path.

    scripts/ is not a package, and putting it on sys.path would let its ~80
    modules shadow the standard library, so load the one file we need by name.
    """
    spec = importlib.util.spec_from_file_location("build_terminal_site", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


site = _load_generator()


def _managed_region(html: str, name: str) -> str:
    """The slice of docs/index.html that the builder owns for one region."""
    begin = "<!-- BEGIN:%s (generated by scripts/build_terminal_site.py) -->" % name
    end = "<!-- END:%s -->" % name
    assert html.count(begin) == 1, "index.html needs exactly one %s marker" % name
    assert html.count(end) == 1, "index.html needs exactly one END %s marker" % name
    return html.split(begin, 1)[1].split(end, 1)[0]


def _payload() -> dict:
    text = DATA_JS.read_text(encoding="utf-8")
    assert text.startswith("/*"), "data.js must carry its generated-by header"
    body = text.split(PRELUDE, 1)[1].rstrip().rstrip(";")
    return json.loads(body)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def test_page_and_assets_are_present():
    for name in ("index.html", "assets/terminal.css", "assets/terminal.js", "assets/data.js"):
        path = DOCS / name
        assert path.exists(), name + " missing"
        assert path.stat().st_size > 0, name + " is empty"


def test_nojekyll_is_present_so_pages_serves_the_files_raw():
    """Without .nojekyll the markdown reports would be swallowed by Jekyll."""
    marker = DOCS / ".nojekyll"
    assert marker.exists(), "docs/.nojekyll is required for the Pages build"


def test_data_js_is_a_json_payload_with_the_expected_shape():
    payload = _payload()
    for key in ("repo", "counts", "pipeline", "gates", "weeks", "figures"):
        assert key in payload, "payload misses " + key
    assert len(payload["weeks"]) == 20
    assert len(payload["pipeline"]) == 5
    assert payload["counts"]["weeks"] == 20


def test_figure_payload_covers_exactly_the_repository_figures():
    payload = _payload()
    on_disk = sorted(p.name for p in REPO_FIGURES.glob("*.png"))
    listed = sorted(row["file"] for row in payload["figures"])
    assert listed == on_disk, "the site and outputs/figures/ disagree on the figure set"
    assert len(listed) == 42


def test_every_figure_has_a_caption_and_a_hash():
    for row in _payload()["figures"]:
        assert row["caption"].strip(), row["file"] + " has no caption"
        assert re.fullmatch(r"[0-9a-f]{64}", row["sha"]), row["file"] + " has no sha256"


def test_copied_figures_are_byte_identical_to_the_repository_copies():
    for row in _payload()["figures"]:
        published = FIGURE_DIR / row["file"]
        assert published.exists(), "not copied into docs/: " + row["file"]
        assert published.stat().st_size == row["bytes"]
        assert _sha256(published) == row["sha"], row["file"] + " drifted from the repository copy"


def test_every_week_points_at_a_report_that_exists():
    for week in _payload()["weeks"]:
        assert (REPO_ROOT / week["doc"]).exists(), week["doc"] + " is missing"
        assert week["summary"].strip(), "week %d has no summary" % week["n"]
        assert week["stage"].strip() and week["title"].strip()


def test_week_numbers_are_one_to_twenty():
    numbers = [w["n"] for w in _payload()["weeks"]]
    assert numbers == list(range(1, 21))


def test_latest_week_tag_is_verbatim_from_its_own_report():
    """The latest week's one-liner must be a literal slice of section 0.

    Only the emphasis markers (``**``) and the inline code ticks are removed;
    the site may not paraphrase a headline, and it may not invent a number.
    """
    week = _payload()["weeks"][-1]
    assert week["n"] == 20 and week["doc"] == "docs/30_week20_report.md"
    lines = (REPO_ROOT / week["doc"]).read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith("## 0."))
    end = next(i for i, line in enumerate(lines) if i > start and line.startswith("## "))
    plain = "\n".join(lines[start + 1:end]).replace("**", "").replace("`", "")
    assert week["tag"] in plain, "the week-20 tag is not verbatim from the report"


def test_gate_payload_matches_the_frozen_gate_records():
    gates = {g["name"].split(" - ")[0]: g for g in _payload()["gates"]}
    assert gates["Gate 0"]["status"] == "CLOSED"
    assert gates["Gate 0"]["blockers"] == []
    assert gates["Gate 1"]["status"] == "NOT CLOSED"
    assert gates["Gate 1"]["blockers"], "an open gate must name its blocker"
    record = (REPO_ROOT / "outputs" / "week2" / "gate1_record.md").read_text(encoding="utf-8")
    assert "NOT CLOSED" in record


def test_page_references_only_files_inside_the_published_folder():
    """Anything the browser fetches must live under docs/."""
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    for match in re.findall(r'(?:src|href)="([^"]+)"', html):
        if match.startswith(("http://", "https://", "#", "data:", "mailto:")):
            continue
        target = match.split("#", 1)[0].split("?", 1)[0]
        if not target:
            continue
        assert (DOCS / target).exists(), "index.html points outside docs/: " + match


def test_site_pulls_no_external_assets():
    """No CDN, no fonts, no analytics: a self-contained static folder."""
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    css = (ASSETS / "terminal.css").read_text(encoding="utf-8")
    js = (ASSETS / "terminal.js").read_text(encoding="utf-8")
    assert not re.search(r'<script[^>]+src="https?://', html)
    assert not re.search(r'<link[^>]+href="https?://', html)
    assert not re.search(r"@import\s+url\(\s*['\"]?https?://", css)
    assert not re.search(r"\bfetch\(\s*['\"]https?://", js)
    assert "googleapis" not in html + css + js
    assert "analytics" not in html.lower()


def test_page_is_usable_without_a_pointer():
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    assert 'role="log"' in html and 'aria-live="polite"' in html
    assert '<label class="ps1" for="cmd"' in html
    assert "<noscript>" in html, "the terminal needs a no-JS fallback"


def test_terminal_js_defines_the_commands_it_advertises():
    js = (ASSETS / "terminal.js").read_text(encoding="utf-8")
    for name in ("help", "about", "status", "pipeline", "weeks", "cat", "read",
                 "figures", "open", "theme", "repo", "contacts"):
        assert "CMDS." + name + " =" in js, "missing command: " + name
    listed = js.split("CMDS.help = function () {", 1)[1].split("};", 1)[0]
    for label in ("about", "status", "pipeline", "weeks", "cat", "read", "figures", "open"):
        assert label in listed, "help does not mention " + label


def test_terminal_js_derives_the_week_and_figure_counts():
    """Stale counts are the quiet way a generated page starts to lie.

    ``terminal.js`` is a hand-maintained asset (unlike ``data.js``), so nothing
    else stops a "12 周" from surviving week 13.  It must read the numbers out
    of the payload it was served with.
    """

    js = (ASSETS / "terminal.js").read_text(encoding="utf-8")
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    for stale in ("12 \u5468", "13 \u5468", "14 \u5468", "26 \u5f20\u56fe",
                  "28 \u5f20\u56fe", "30 \u5f20\u56fe", "open F24", "cat 12", "cat 14",
                  "week 12 / Stage 13", "Week 14 / Stage 15"):
        assert stale not in js, "hard-coded reference in terminal.js: " + stale
    for expression in ("COUNTS.weeks + ", "FIGS.length + ", "LAST_WEEK.n", "LAST_FIG.id"):
        assert expression in js, "terminal.js does not derive: " + expression

    # index.html is a hand-maintained asset too, so its prose must not name a
    # week that has since been superseded -- the numbers it shows are spans that
    # ``fillDynamic()`` overwrites from the payload at boot.  The latest-report
    # link is deliberately *not* pinned to a filename here; the payload names
    # it, and test_latest_week_report_link_resolves_without_hardcoding pins the
    # mechanism instead of a particular week.
    for stale in ("Week 12 / Stage 13", "cat 12",
                  "Week 14 / Stage 15", "cat 14"):
        assert stale not in html, "stale week reference in index.html: " + stale
    for hook in ('class="js-weeks"', 'class="js-figures"', 'class="js-latest"',
                 'id="chip-report-latest"', 'id="chip-cat-latest"'):
        assert hook in html, "index.html misses the dynamic hook " + hook
    for hook in ("function fillDynamic()", '.js-weeks', 'chip-report-latest',
                 'chip-cat-latest'):
        assert hook in js, "terminal.js does not fill " + hook
    assert "fillDynamic();" in js, "boot() never calls fillDynamic()"


def test_check_mode_reports_the_site_as_consistent():
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=300,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert "OK" in result.stdout


def test_404_page_exists_and_stays_inside_the_published_folder():
    """404.html is served from the site root for *any* missing path.

    On a project Pages site a root-absolute ``href="/"`` or ``src="/..."``
    resolves against the user-site root, not ``/electrolyte-ranking-stability/``
    -- exactly how the first version lost its stylesheet and its way home.
    """
    page = DOCS / "404.html"
    assert page.exists(), "docs/404.html is required by GitHub Pages"
    html = page.read_text(encoding="utf-8")
    assert 'href="/"' not in html, '404.html must not link to the user-site root'
    assert 'src="/' not in html, "404.html must not use a root-absolute asset path"
    assert "assets/terminal.css" in html, "404.html must still load the stylesheet"
    assert "data.js" not in html, "the 404 must not depend on the payload to stay styled"
    for match in re.findall(r'(?:src|href)="([^"]+)"', html):
        if match.startswith(("http://", "https://", "#", "data:", "mailto:")):
            continue
        target = match.split("#", 1)[0].split("?", 1)[0]
        if not target or not target.strip("./"):
            continue
        assert (DOCS / target).exists(), "404.html points outside docs/: " + match


def test_404_counts_are_written_by_the_generator():
    """The stale "12 周、26 张图" now follows the payload, not a hand edit."""
    payload = _payload()
    html = (DOCS / "404.html").read_text(encoding="utf-8")
    assert ("%d 周" % payload["counts"]["weeks"]) in html
    assert ("%d 张图" % payload["counts"]["figures"]) in html


def test_index_html_does_not_handcode_a_week_report_link():
    """A report path may only come out of the generator's managed region.

    Adding a week must not leave a dead report filename behind in hand-written
    markup: the only place such a path may appear is the generated argument
    timeline, and every path there has to be one the payload knows about.
    """
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    payload = _payload()
    known = {w["doc"] for w in payload["weeks"]}
    found = set(re.findall(r"docs/[\w./-]*_report\.md", html))
    assert found <= known, (
        "index.html links a report outside the payload: " + str(sorted(found - known)))
    outside = re.findall(r"docs/[\w./-]*_report\.md",
                         html.replace(_managed_region(html, "argument-timeline"), ""))
    assert not outside, ("report link outside the generated timeline: "
                         + str(sorted(set(outside))))
    assert 'id="chip-report-latest"' in html, "the report chip needs its dynamic id"


def test_latest_week_report_link_resolves_without_hardcoding():
    payload = _payload()
    last = payload["weeks"][-1]
    assert (REPO_ROOT / last["doc"]).exists(), last["doc"] + " is missing"
    js = (ASSETS / "terminal.js").read_text(encoding="utf-8")
    assert "chip-report-latest" in js, "fillDynamic must rewrite the report chip"
    assert "last.doc" in js, "the report link must be taken from the payload"


def test_gallery_and_search_are_real_commands():
    js = (ASSETS / "terminal.js").read_text(encoding="utf-8")
    for name in ("gallery", "search"):
        assert re.search(r"\bCMDS\.%s\s*=" % name, js), "missing command: " + name
    # thumbnails must defer offscreen work and reserve their box, or the grid
    # reflows line by line as the bitmaps arrive.
    assert 'loading="lazy"' in js, "gallery thumbnails must lazy-load"
    css = (ASSETS / "terminal.css").read_text(encoding="utf-8")
    assert "aspect-ratio" in css, "gallery cells must reserve their aspect ratio"
    assert ".gallery" in css and ".gcell" in css, "gallery styles are missing"


def test_terminal_js_wires_deep_links_and_browser_history():
    js = (ASSETS / "terminal.js").read_text(encoding="utf-8")
    assert "window.history.replaceState" in js, "open/cat must write the address bar"
    assert 'addEventListener("popstate"' in js, "back/forward must re-route"
    assert "fig=" in js and "w=" in js, "?fig= / ?w= deep links must be parsed"


# ------------------------------------------------- index.html: managed regions
# The page is hand-maintained, but the numbers and the week-by-week argument
# inside it are spliced in from the same payload the terminal reads.  These
# tests pin the two ways that splice can go quiet: a marker stolen or lost, and
# a region that no longer matches what the builder would write today.

def test_index_html_carries_every_managed_marker_exactly_once():
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    for name in MANAGED_BLOCKS:
        _managed_region(html, name)


def test_index_html_managed_regions_match_the_generator():
    """The --check discipline, run in-process: a stale region is a failure."""
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    rendered = dict(site.managed_blocks(_payload()))
    assert set(rendered) == set(MANAGED_BLOCKS), (
        "the builder and the page disagree about which regions exist")
    for name in MANAGED_BLOCKS:
        assert _managed_region(html, name).strip("\n") == rendered[name].strip("\n"), (
            "index.html region %r is stale; rerun scripts/build_terminal_site.py" % name)


def test_argument_timeline_has_one_row_per_week_with_a_docs_link():
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    weeks = _payload()["weeks"]
    block = _managed_region(html, "argument-timeline")
    rows = re.findall(r'<li class="argue-row" data-week="(\d+)">(.*?)</li>', block, re.S)
    assert rows, "the argument timeline rendered no rows"
    assert {int(n) for n, _ in rows} == {w["n"] for w in weeks}, (
        "the timeline does not cover every week in the payload")
    assert [int(n) for n, _ in rows] == [w["n"] for w in weeks], (
        "the timeline is not in week order")
    for number, row in rows:
        assert re.search(r">Week ", row), "week %s row lost its week label" % number
        hrefs = re.findall(r'href="([^"]+)"', row)
        assert any("/docs/" in h and h.endswith(".md") for h in hrefs), (
            "week %s row carries no docs/ report link" % number)


def test_index_html_static_numbers_track_the_payload():
    """What a crawler or a JS-off reader sees must equal the payload's truth.

    This is the regression that shipped: the brief advertised "1265 ORCA jobs"
    while the payload counted 1319, and nothing noticed, because the span was
    overwritten at boot by a script the crawler never runs.
    """
    payload = _payload()
    counts = payload["counts"]
    last = payload["weeks"][-1]
    html = (DOCS / "index.html").read_text(encoding="utf-8")

    expected = {
        "js-weeks": str(counts["weeks"]),
        "js-figures": str(counts["figures"]),
        "js-orca": str(counts["orca_out"]),
        "js-tests": str(counts["tests_passed"]),
        "js-latest-week": str(last["n"]),
        "js-latest": "Week %d / %s" % (last["n"], last["stage"]),
    }
    seen = {key: [] for key in expected}
    for match in re.finditer(r'<span class="(js-[a-z-]+)">([^<]*)</span>', html):
        if match.group(1) in seen:
            seen[match.group(1)].append(match.group(2))
    for key, want in sorted(expected.items()):
        assert seen[key], "index.html renders no %s value" % key
        for got in seen[key]:
            assert got == want, "%s shows %r but the payload says %r" % (key, got, want)

    cats = re.findall(r'data-cmd="cat (\d+)"', html)
    assert cats, "the latest-week chip lost its data-cmd hook"
    assert set(cats) == {str(last["n"])}, (
        "the cat chip points at %s but the latest week is %d"
        % (sorted(set(cats)), last["n"]))

    meta = re.search(r'<meta name="description" content="([^"]*)"', html)
    assert meta, "index.html lost its meta description"
    assert "%d 周" % counts["weeks"] in meta.group(1)
    assert "%d 张图" % counts["figures"] in meta.group(1)


def test_noscript_fallback_counts_track_the_payload():
    html = (DOCS / "index.html").read_text(encoding="utf-8")
    block = _managed_region(html, "static-fallbacks")
    assert "<noscript>" in block and "</noscript>" in block
    payload = _payload()
    assert ('<span class="js-weeks">%d</span>' % payload["counts"]["weeks"]) in block
    for gate in payload["gates"]:
        assert gate["status"] in block, "the noscript fallback omits " + gate["status"]
        for blocker in gate["blockers"]:
            assert blocker in block, "the noscript fallback omits a gate blocker"
