#!/usr/bin/env python
"""Stage 5 / T4 step 1 -- Li+ coordination motif enumeration for the C1 state.

This module implements, in the order written there, the frozen rule
``conformers_and_states.li_motif_generation`` of
``config/scientific_definitions.yaml`` (frozen: true, do not edit):

    1. identify O/N/S/P donor atoms
    2. one monodentate Li+ site per donor
    3. bidentate candidates for the geometrically allowed donor pairs
    4. supplement with the molecular ESP minima
    5. GFN2-xTB pre-optimisation
    6. dedup by Li-donor connectivity / key distances / structural similarity / energy
    7. the surviving low-energy motifs are the ones that go to DFT

Why this is code and not judgement
----------------------------------
Motif enumeration is the most subjective step of Stage 5, so it is the step that
has to be reproducible: every candidate below is generated by a written-down
rule, pre-optimised with the same frozen xTB used everywhere else, and recorded
together with the numbers that decided its fate. A candidate that is generated
and then dropped is still written to the CSV -- dropping it silently would be
the same class of error as deleting a failed SCF.

Donor rule
----------
An atom is a donor when it can offer a lone pair to Li+:

* every oxygen (carbonyl, ether, sulfoxide-O, sulfone-O, phosphate-O);
* a nitrogen with a triple bond (nitrile) or with at most two heavy neighbours;
* sulfur only when it carries no double-bonded oxygen, i.e. a sulfone or
  sulfoxide sulfur is NOT a donor -- its oxygens are;
* phosphorus only when it carries no double-bonded oxygen, i.e. a phosphate
  phosphorus is not a donor -- its oxygens are.

The derived donor elements are compared per molecule with the frozen
``donor_atoms`` column of ``data/metadata/core_set.csv`` and the verdict is
stored in every row (``donor_rule_check``), so a disagreement is visible.

Geometry convention
-------------------
All distances are Angstrom. The parent geometry is always the shared G1
(GFN2-xTB) geometry of ``outputs/_week3_scratch``; motif work never rebuilds it,
so C0 and C1 are anchored on the same parent structure.

Outputs
-------
``structures/li_motifs/<NAME>_m<k>.xyz``   one file per surviving motif
``outputs/week5/li_motif_generation.csv``  one row per (molecule, candidate)
``outputs/week5/li_motif_generation.json`` run record (versions, counts, rule)
``outputs/week5/li_motif_generation.md``   human-readable motif table
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from electrolyte_ranking import toolchain, xtb  # noqa: E402
from run_core_set_p1 import cached_geometries  # noqa: E402

CORE_SET = REPO_ROOT / "data" / "metadata" / "core_set.csv"
DEFAULT_OUTDIR = REPO_ROOT / "outputs" / "week5"
DEFAULT_STRUCTDIR = REPO_ROOT / "structures" / "li_motifs"
DEFAULT_SCRATCH = REPO_ROOT / "outputs" / "_week5_scratch"

EH_TO_KJ = 2625.4996394799

#: The 8-10 representative molecules of docs/08 section 7 (T4): one molecule per
#: structural family of the core set (8 families), plus a second ether and a
#: second nitrile so that denticity shows up INSIDE a family instead of being
#: confounded with it. DME is the bidentate 2xO chelator, DOL the monodentate
#: cyclic ether, AN the monodentate N donor, and SN the dinitrile whose two
#: nitrogens are not geometrically able to chelate one Li+. DME is also the
#: frozen primary reference ligand R and AN the secondary one, so the
#: ligand-exchange leg of Stage 5 needs no extra molecules.
#:
#: All ten are inside the T2/T3 audit subset, so the C0 reference (r2SCAN-3c
#: vertical IP/EA at the G2 geometry) already exists for every one of them and
#: the coordination step only adds the C1 state.
C1_NAMES = ("EC", "DMC", "DME", "DOL", "GBL", "SL", "DMSO", "AN", "SN", "TMP")

#: Frozen primary / secondary reference ligand of config/scientific_definitions.yaml.
PRIMARY_R = "DME"
SECONDARY_R = "AN"

#: Target Li-donor distance used when the initial site is placed (Angstrom).
PLACEMENT_DISTANCE = {"O": 1.90, "N": 2.00, "S": 2.30, "P": 2.30}

#: A heavy atom counts as bonded to Li when it is inside this radius after pre-opt.
CONTACT_CUTOFF = 2.60

#: Two initial sites closer than this are treated as the same site.
SITE_MERGE_DISTANCE = 0.80

#: Donor pairs further apart than this cannot bridge one Li+ at a chemical distance.
BIDENTATE_MAX_DONOR_DISTANCE = 4.60

#: Covalent radii (Angstrom) used only for the parent-bond-integrity check.
COVALENT_RADIUS = {
    "H": 0.31, "C": 0.76, "N": 0.71, "O": 0.66, "F": 0.57,
    "P": 1.07, "S": 1.05, "Li": 1.28,
}
BOND_INTACT_FACTOR = 1.30
COLUMNS = [
    "mol_id",
    "name",
    "family",
    "candidate_id",
    "placement",
    "donor_indices",
    "donor_symbols",
    "target_distance_a",
    "preopt_status",
    "preopt_energy_eh",
    "preopt_energy_rel_kj",
    "n_donor_contacts",
    "contact_donor_indices",
    "li_min_distance_a",
    "parent_bonds_intact",
    "kept",
    "dedup_reason",
    "motif_id",
    "motif_path",
    "donor_rule_check",
    "qc_flags",
    "seconds",
    "error",
]


# ---------------------------------------------------------------------------
# small geometry helpers
# ---------------------------------------------------------------------------
def read_xyz(path: Path):
    """Return (symbols, coords) from an XYZ file, both in file order."""

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    index = 0
    while index < len(lines) and not lines[index].strip():
        index += 1
    count = int(lines[index].strip())
    symbols = []
    coords = []
    for line in lines[index + 2 : index + 2 + count]:
        parts = line.split()
        symbols.append(parts[0])
        coords.append([float(parts[1]), float(parts[2]), float(parts[3])])
    return symbols, np.asarray(coords, dtype=float)


def format_xyz(symbols, coords, comment: str) -> str:
    lines = [str(len(symbols)), comment]
    for symbol, (x, y, z) in zip(symbols, coords):
        lines.append("%-2s %16.10f %16.10f %16.10f" % (symbol, x, y, z))
    return chr(10).join(lines) + chr(10)


def write_xyz(path: Path, symbols, coords, comment: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(format_xyz(symbols, coords, comment), encoding="utf-8", newline=chr(10))


def unit(vector):
    norm = float(np.linalg.norm(vector))
    if norm < 1e-9:
        return None
    return vector / norm


def kabsch_rmsd(first, second) -> float:
    """Heavy-atom RMSD after optimal superposition (rotation only, no reflection)."""

    first_centred = first - first.mean(axis=0)
    second_centred = second - second.mean(axis=0)
    covariance = first_centred.T @ second_centred
    left, _, right = np.linalg.svd(covariance)
    determinant = np.sign(np.linalg.det(left @ right))
    correction = np.diag([1.0, 1.0, determinant])
    rotated = first_centred @ (left @ correction @ right)
    return float(np.sqrt(np.mean(np.sum((rotated - second_centred) ** 2, axis=1))))


# ---------------------------------------------------------------------------
# donor identification (frozen rule, step 1)
# ---------------------------------------------------------------------------
def heavy_graph(smiles: str):
    """(symbols, neighbours) of the heavy atoms, in SMILES order.

    ``scripts/run_xtb_job.build_geometry`` embeds with ``Chem.AddHs`` and RDKit
    keeps the heavy atoms in SMILES order with hydrogens appended, so heavy atom
    i of the SMILES graph is atom i of the stored XYZ. That is asserted in
    ``check_heavy_order`` rather than trusted.
    """

    from rdkit import Chem

    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        raise ValueError("RDKit could not parse SMILES " + repr(smiles))
    symbols = [atom.GetSymbol() for atom in molecule.GetAtoms()]
    neighbours = defaultdict(list)
    for bond in molecule.GetBonds():
        first = bond.GetBeginAtomIdx()
        second = bond.GetEndAtomIdx()
        order = bond.GetBondTypeAsDouble()
        neighbours[first].append((second, order))
        neighbours[second].append((first, order))
    return symbols, neighbours


def check_heavy_order(symbols_h, smiles: str) -> None:
    expected, _ = heavy_graph(smiles)
    if list(symbols_h[: len(expected)]) != expected:
        raise ValueError(
            "XYZ heavy-atom order does not match the SMILES graph of "
            + smiles
            + ": "
            + "".join(symbols_h[: len(expected)])
            + " vs "
            + "".join(expected)
        )


def find_donors(symbols_h, neighbours) -> list:
    """Indices of heavy atoms that can offer a lone pair (see module docstring)."""

    donors = []
    for index, symbol in enumerate(symbols_h):
        if symbol == "O":
            donors.append(index)
        elif symbol == "N":
            orders = [order for _, order in neighbours[index]]
            if len(neighbours[index]) <= 2 or any(order >= 3 for order in orders):
                donors.append(index)
        elif symbol in ("S", "P"):
            double_to_oxygen = any(
                symbols_h[other] == "O" and order >= 2
                for other, order in neighbours[index]
            )
            if not double_to_oxygen:
                donors.append(index)
    return donors


def donor_rule_check(symbols_h, donors, metadata_tokens: str) -> str:
    """Compare the derived donor elements with the frozen ``donor_atoms`` column."""

    derived = sorted({symbols_h[index] for index in donors})
    expected = sorted(
        {
            token.strip()[0]
            for token in (metadata_tokens or "").split(";")
            if token.strip()
        }
    )
    if derived == expected:
        return "elements_match"
    return "elements_mismatch derived=" + "".join(derived) + " metadata=" + "".join(expected)


def lone_pair_direction(index, symbols, neighbours, coords):
    """Unit vector pointing away from the donor's bonded neighbours."""

    bonded = [other for other, _ in neighbours[index]]
    if not bonded:
        return None
    vectors = [unit(coords[other] - coords[index]) for other in bonded]
    if any(vector is None for vector in vectors):
        return None
    return unit(-np.sum(vectors, axis=0))

# ---------------------------------------------------------------------------
# site generation (frozen rule, steps 2-4)
# ---------------------------------------------------------------------------
def monodentate_sites(donors, symbols, neighbours, coords):
    sites = []
    for index in donors:
        direction = lone_pair_direction(index, symbols, neighbours, coords)
        if direction is None:
            continue
        distance = PLACEMENT_DISTANCE.get(symbols[index], 2.00)
        sites.append(
            {
                "placement": "monodentate",
                "donors": (index,),
                "target_distance": distance,
                "position": coords[index] + distance * direction,
            }
        )
    return sites


def bidentate_sites(donors, symbols, neighbours, coords):
    """Li+ equidistant from two donors, on the bisector side facing outward."""

    centroid = coords.mean(axis=0)
    sites = []
    for position, first in enumerate(donors):
        for second in donors[position + 1 :]:
            separation = float(np.linalg.norm(coords[first] - coords[second]))
            if separation > BIDENTATE_MAX_DONOR_DISTANCE:
                continue
            first_dir = lone_pair_direction(first, symbols, neighbours, coords)
            second_dir = lone_pair_direction(second, symbols, neighbours, coords)
            if first_dir is None or second_dir is None:
                continue
            bisector = unit(first_dir + second_dir)
            axis = unit(coords[second] - coords[first])
            if bisector is None or axis is None:
                continue
            perpendicular = unit(bisector - float(np.dot(bisector, axis)) * axis)
            middle = 0.5 * (coords[first] + coords[second])
            target = 0.5 * (
                PLACEMENT_DISTANCE.get(symbols[first], 2.00)
                + PLACEMENT_DISTANCE.get(symbols[second], 2.00)
            )
            half = 0.5 * separation
            if perpendicular is None or half >= target:
                # The two donors are too far apart to bridge one Li+ at a
                # chemical Li-donor distance. The candidate is kept anyway, sat
                # on the perpendicular bisector, and the xTB pre-opt decides
                # whether it survives or collapses onto a monodentate minimum.
                candidate = middle
                placement = "bidentate_long"
            else:
                offset = math.sqrt(target * target - half * half)
                placements = [
                    middle + offset * perpendicular,
                    middle - offset * perpendicular,
                ]
                candidate = max(
                    placements,
                    key=lambda point: float(np.linalg.norm(point - centroid)),
                )
                placement = "bidentate"
            sites.append(
                {
                    "placement": placement,
                    "donors": (first, second),
                    "target_distance": target,
                    "position": candidate,
                }
            )
    return sites


def read_esp_grid(path: Path) -> list:
    """(sigma, position) for every surface segment of an xtb --esp COSMO file.

    Columns are: index, type, x, y, z, sigma, area, sigma, 0.0. sigma is the
    segment charge density, i.e. the electrostatic potential on the vdW grid up
    to the constant factor xtb applies when it prints its ESP report; the
    regression test pins that factor down against a real xTB output.
    """

    points = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        parts = line.split()
        if len(parts) < 8 or not parts[0].isdigit():
            continue
        try:
            sigma = float(parts[5])
            position = np.asarray([float(parts[2]), float(parts[3]), float(parts[4])])
        except ValueError:
            continue
        points.append((sigma, position))
    points.sort(key=lambda item: item[0])
    return points


def esp_sites(parent_xyz: Path, donors, symbols, coords, executable, workdir: Path) -> list:
    """Supplement the sites with the molecular ESP minima (frozen rule step 4).

    ``xtb --esp`` writes ``xtb_esp.cosmo``, whose surface segments carry the
    electrostatic potential on the vdW grid in their sigma column (xtb prints
    the same numbers scaled by ten in its own ESP report; the regression test
    pins that factor down). The most negative sigma is therefore the most
    attractive point for a cation on that grid. Its position is mapped back to
    the nearest donor and turned into one more initial site, so a donor whose
    lone-pair direction was mis-guessed can still be recovered.
    """

    if executable is None:
        return []
    workdir.mkdir(parents=True, exist_ok=True)
    probe = workdir / parent_xyz.name
    probe.write_text(
        parent_xyz.read_text(encoding="utf-8"), encoding="utf-8", newline=chr(10)
    )
    completed = toolchain.run_command(
        executable,
        [parent_xyz.name, "--esp", "--gfn", "2"],
        cwd=workdir,
        timeout_seconds=900.0,
        environment=xtb.xtb_thread_environment(),
    )
    cosmo = workdir / "xtb_esp.cosmo"
    if not cosmo.exists():
        text = (completed.stdout or "") + (completed.stderr or "")
        (workdir / "esp.log").write_text(text, encoding="utf-8", newline=chr(10))
        return []
    points = read_esp_grid(cosmo)
    if not points:
        return []
    sites = []
    seen = set()
    for sigma, position in points[:24]:
        distances = [float(np.linalg.norm(position - coords[index])) for index in donors]
        donor_index = donors[int(np.argmin(distances))]
        direction = unit(position - coords[donor_index])
        if direction is None:
            continue
        key = (
            donor_index,
            int(round(float(direction[0]) * 4)),
            int(round(float(direction[1]) * 4)),
            int(round(float(direction[2]) * 4)),
        )
        if key in seen:
            continue
        seen.add(key)
        distance = PLACEMENT_DISTANCE.get(symbols[donor_index], 2.00)
        sites.append(
            {
                "placement": "esp_min",
                "donors": (donor_index,),
                "target_distance": distance,
                "position": coords[donor_index] + distance * direction,
                "sigma": sigma,
            }
        )
        if len(sites) >= 3:
            break
    return sites


def merge_sites(sites):
    """Drop sites that sit on top of each other (frozen rule step 6, first pass)."""

    merged = []
    for site in sites:
        if any(
            float(np.linalg.norm(site["position"] - kept["position"])) < SITE_MERGE_DISTANCE
            for kept in merged
        ):
            continue
        merged.append(site)
    return merged

# ---------------------------------------------------------------------------
# xTB pre-optimisation (step 5) and QC
# ---------------------------------------------------------------------------
def parent_bonds_intact(symbols_h, neighbours, coords) -> bool:
    """True when no covalent bond of the parent molecule was broken."""

    for index in range(len(symbols_h)):
        for other, _ in neighbours[index]:
            if other <= index:
                continue
            limit = BOND_INTACT_FACTOR * (
                COVALENT_RADIUS.get(symbols_h[index], 0.8)
                + COVALENT_RADIUS.get(symbols_h[other], 0.8)
            )
            if float(np.linalg.norm(coords[index] - coords[other])) > limit:
                return False
    return True


def relax_candidate(name, parent_xyz, site, args, index) -> dict:
    """One GFN2-xTB optimisation of the [Li M]+ complex started from ``site``."""

    symbols_h, coords_h = read_xyz(parent_xyz)
    symbols = list(symbols_h) + ["Li"]
    coords = np.vstack([coords_h, site["position"]])
    label = name + "_cand%02d" % index
    workdir = Path(args.scratch) / name / label
    workdir.mkdir(parents=True, exist_ok=True)
    xyz_path = workdir / (label + ".xyz")
    write_xyz(xyz_path, symbols, coords, label + " " + site["placement"])
    started = time.perf_counter()
    payload = {
        "candidate_id": "c%02d" % index,
        "placement": site["placement"],
        "donor_indices": list(site["donors"]),
        "target_distance": site["target_distance"],
    }
    try:
        result = xtb.run_xtb(
            args.xtb_executable,
            xtb.JOB_OPTIMIZE,
            input_name=xyz_path.name,
            charge=1,
            multiplicity=1,
            cwd=workdir,
            timeout_seconds=args.timeout,
            required=(),
        )
    except Exception as exc:  # noqa: BLE001 - a failed pre-opt is a result, not a crash
        payload.update(
            {
                "status": "execution_failed",
                "energy_eh": None,
                "optimized": None,
                "qc_flags": ["geometry_failed"],
                "error": repr(exc),
                "seconds": round(time.perf_counter() - started, 2),
            }
        )
        return payload
    raw_path = workdir / (label + "_opt.out")
    raw_path.write_text(result.raw_output, encoding="utf-8", newline=chr(10))
    optimized_path = workdir / "xtbopt.xyz"
    optimized = None
    if optimized_path.exists():
        _, optimized = read_xyz(optimized_path)
    payload.update(
        {
            "status": "ok" if result.normal_termination else "abnormal_termination",
            "energy_eh": result.total_energy_eh,
            "optimized": optimized,
            "qc_flags": list(result.qc_flags),
            "error": "",
            "seconds": round(time.perf_counter() - started, 2),
        }
    )
    return payload


def candidate_record(row, symbols_h, neighbours, site, payload, rule_check, global_donors):
    """Everything the CSV needs for one candidate, including the QC verdict."""

    donors = list(site["donors"])
    optimized = payload.get("optimized")
    flags = list(payload.get("qc_flags") or [])
    contacts = []
    donor_contacts = []
    li_min = None
    intact = None
    if optimized is not None:
        distances = [
            float(np.linalg.norm(optimized[-1] - optimized[index]))
            for index in range(len(symbols_h))
        ]
        contacts = [index for index, value in enumerate(distances) if value <= CONTACT_CUTOFF]
        li_min = min(distances)
        intact = parent_bonds_intact(symbols_h, neighbours, optimized[: len(symbols_h)])
        if not intact:
            flags.append("dissociated_optimized_product")
        # Connectivity is the set of DONOR atoms that actually carry Li, not the
        # set the initial site asked for: a monodentate start that slides into a
        # chelate has reached the same motif as the chelate start, and the two
        # must be recorded as one motif rather than as two "different" ones.
        donor_contacts = [index for index in contacts if index in set(global_donors)]
        if not donor_contacts:
            flags.append("no_intact_minimum_found")
        elif set(donor_contacts) != set(donors):
            flags.append("motif_switch")
    return {
        "mol_id": row["mol_id"],
        "name": row["name"],
        "family": row.get("family", ""),
        "candidate_id": payload["candidate_id"],
        "placement": payload["placement"],
        "donor_indices": ";".join(str(index) for index in donors),
        "donor_symbols": "".join(symbols_h[index] for index in donors),
        "target_distance_a": "%.3f" % payload["target_distance"],
        "preopt_status": payload["status"],
        "preopt_energy_eh": payload["energy_eh"],
        "preopt_energy_rel_kj": None,
        "n_donor_contacts": len(donor_contacts),
        "contact_donor_indices": ";".join(str(index) for index in donor_contacts),
        "li_min_distance_a": li_min,
        "parent_bonds_intact": intact,
        "kept": False,
        "dedup_reason": "",
        "motif_id": "",
        "motif_path": "",
        "donor_rule_check": rule_check,
        "qc_flags": ";".join(sorted(set(flags))),
        "seconds": payload["seconds"],
        "error": payload["error"],
        "optimized": optimized,
        "contacts": tuple(sorted(contacts)),
        "donor_contacts": tuple(sorted(donor_contacts)),
        "donors": tuple(sorted(donors)),
    }

# ---------------------------------------------------------------------------
# dedup (frozen rule step 6) and selection (step 7)
# ---------------------------------------------------------------------------
def select_motifs(records, energy_window_kj: float, max_motifs: int):
    """Keep the lowest-energy candidate per Li connectivity, then the window survivors."""

    usable = [
        record
        for record in records
        if record["preopt_status"] == "ok"
        and record["optimized"] is not None
        and record["preopt_energy_eh"] is not None
        and record["donor_contacts"]
        and record["parent_bonds_intact"]
    ]
    usable_ids = {id(record) for record in usable}
    for record in records:
        if id(record) in usable_ids:
            continue
        if record["preopt_status"] != "ok":
            record["dedup_reason"] = "preopt_not_ok"
        elif record["optimized"] is None:
            record["dedup_reason"] = "no_optimized_geometry"
        elif record["preopt_energy_eh"] is None:
            record["dedup_reason"] = "no_energy"
        elif not record["donor_contacts"]:
            record["dedup_reason"] = "no_donor_contact"
        else:
            record["dedup_reason"] = "parent_bonds_broken"

    best_by_connectivity = defaultdict(list)
    for record in usable:
        best_by_connectivity[record["donor_contacts"]].append(record)
    survivors = []
    for group in best_by_connectivity.values():
        group.sort(key=lambda item: item["preopt_energy_eh"])
        winner = group[0]
        for loser in group[1:]:
            first = loser["optimized"][:-1]
            second = winner["optimized"][:-1]
            same_geometry = (
                first.shape == second.shape and kabsch_rmsd(first, second) < 0.25
            )
            loser["dedup_reason"] = (
                "duplicate_geometry_of_" + winner["candidate_id"]
                if same_geometry
                else "duplicate_connectivity_of_" + winner["candidate_id"]
            )
        survivors.append(winner)

    survivors.sort(key=lambda item: item["preopt_energy_eh"])
    if not survivors:
        return []
    reference = survivors[0]["preopt_energy_eh"]
    kept = []
    for record in survivors:
        relative = (record["preopt_energy_eh"] - reference) * EH_TO_KJ
        record["preopt_energy_rel_kj"] = relative
        if relative > energy_window_kj:
            record["dedup_reason"] = "above_energy_window"
        elif len(kept) >= max_motifs:
            record["dedup_reason"] = "beyond_max_motifs"
        else:
            record["kept"] = True
            record["motif_id"] = "m%d" % (len(kept) + 1)
            kept.append(record)
    return kept


# ---------------------------------------------------------------------------
# orchestration
# ---------------------------------------------------------------------------
def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Stage 5 / T4 step 1: Li+ motif enumeration under the frozen "
        "li_motif_generation rule of config/scientific_definitions.yaml."
    )
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--structdir", type=Path, default=DEFAULT_STRUCTDIR)
    parser.add_argument("--scratch", type=Path, default=DEFAULT_SCRATCH)
    parser.add_argument("--only", default=None, help="comma-separated name allow-list")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--jobs", type=int, default=2, help="concurrent xTB processes")
    parser.add_argument("--timeout", type=float, default=900.0)
    # 25 kJ/mol is the value the delivered Stage-5 run used (DMC m2 sits at
    # 24.621 kJ/mol); the default matches it so a plain re-run reproduces the
    # delivered 12 motifs instead of silently dropping to 11.
    parser.add_argument("--energy-window-kj", type=float, default=25.0)
    parser.add_argument("--max-motifs", type=int, default=2)
    parser.add_argument("--skip-esp", action="store_true", help="skip the ESP supplement")
    return parser.parse_args(argv)


def load_core_set(path: Path = CORE_SET) -> list:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def select_rows(rows, only=None, limit=None) -> list:
    by_name = {row["name"]: row for row in rows}
    missing = [name for name in C1_NAMES if name not in by_name]
    if missing:
        raise SystemExit("C1 molecule list missing from core_set.csv: " + ", ".join(missing))
    selected = [by_name[name] for name in C1_NAMES]
    if only:
        wanted = {item.strip() for item in only.split(",") if item.strip()}
        selected = [
            row for row in selected if row["mol_id"] in wanted or row["name"] in wanted
        ]
    if limit is not None:
        selected = selected[:limit]
    return selected


def resolve_g1(row) -> tuple:
    for path, label in cached_geometries(row["mol_id"], row["name"]):
        if path.exists() and path.stat().st_size > 0:
            return path, label
    raise RuntimeError("no cached G1 geometry for " + row["mol_id"] + " " + row["name"])


def relative(path: Path) -> str:
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()

def build_candidates(row, args, executable) -> tuple:
    g1, g1_source = resolve_g1(row)
    symbols_h, coords_h = read_xyz(g1)
    check_heavy_order(symbols_h, row["smiles"])
    _, neighbours = heavy_graph(row["smiles"])
    donors = find_donors(symbols_h, neighbours)
    rule_check = donor_rule_check(symbols_h, donors, row.get("donor_atoms", ""))
    sites = monodentate_sites(donors, symbols_h, neighbours, coords_h)
    sites += bidentate_sites(donors, symbols_h, neighbours, coords_h)
    if not args.skip_esp:
        sites += esp_sites(
            g1,
            donors,
            symbols_h,
            coords_h,
            executable,
            Path(args.scratch) / row["mol_id"] / "_esp",
        )
    return g1, g1_source, symbols_h, neighbours, donors, rule_check, merge_sites(sites)


def run_molecule(row, args, executable) -> list:
    g1, g1_source, symbols_h, neighbours, donors, rule_check, sites = build_candidates(
        row, args, executable
    )

    def work(item):
        index, site = item
        payload = relax_candidate(row["name"], g1, site, args, index)
        return candidate_record(
            row, symbols_h, neighbours, site, payload, rule_check, donors
        )

    records = []
    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        for record in pool.map(work, list(enumerate(sites, start=1))):
            record["g1_geometry"] = relative(g1)
            record["g1_source"] = g1_source
            record["n_donors"] = len(donors)
            records.append(record)

    kept = select_motifs(records, args.energy_window_kj, args.max_motifs)
    for record in kept:
        target = Path(args.structdir) / (row["name"] + "_" + record["motif_id"] + ".xyz")
        comment = " ".join(
            [
                row["mol_id"],
                row["name"],
                "C1",
                record["motif_id"],
                "donors=" + (record["contact_donor_indices"] or "none"),
                "placement=" + record["placement"],
                "rel_kj=%.2f" % record["preopt_energy_rel_kj"],
                "from=" + g1_source,
            ]
        )
        write_xyz(target, list(symbols_h) + ["Li"], record["optimized"], comment)
        record["motif_path"] = relative(target)
    return records


def write_csv(path: Path, records) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [",".join(COLUMNS)]
    for record in records:
        values = []
        for column in COLUMNS:
            value = record.get(column, "")
            if value is None:
                value = ""
            elif isinstance(value, float):
                value = ("%.6f" % value).rstrip("0").rstrip(".")
            elif isinstance(value, bool):
                value = "True" if value else "False"
            text = str(value).replace(",", ";")
            # An ORCA failure tail contains raw newlines; a hand-rolled CSV
            # must not put them in a field or the row is torn in two and any
            # standards-compliant reader (csv.DictReader in analyze_c1_*
            # included) silently loses the tail of the record.
            text = text.replace(chr(13), " ").replace(chr(10), " | ")
            values.append(text)
        lines.append(",".join(values))
    path.write_text(
        chr(10).join(lines) + chr(10),
        encoding="utf-8",
        newline=chr(13) + chr(10),
    )
    return path


def write_markdown(path: Path, records, rows) -> Path:
    by_mol = defaultdict(list)
    for record in records:
        by_mol[record["name"]].append(record)
    lines = [
        "# Stage 5 / T4 step 1 -- Li+ motif generation (frozen rule replay)",
        "",
        "Rule source: config/scientific_definitions.yaml "
        "conformers_and_states.li_motif_generation (frozen: true, do not edit).",
        "",
        "| mol | family | donors | candidates | kept | motifs (donor atoms, rel kJ/mol) | rule check |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        name = row["name"]
        group = by_mol.get(name, [])
        kept = [record for record in group if record["kept"]]
        donor_count = group[0]["n_donors"] if group else 0
        detail = "; ".join(
            "%s: %s (%.2f)"
            % (
                record["motif_id"],
                record["contact_donor_indices"] or "none",
                record["preopt_energy_rel_kj"] or 0.0,
            )
            for record in kept
        )
        check = group[0]["donor_rule_check"] if group else "n/a"
        lines.append(
            "| %s %s | %s | %d | %d | %d | %s | %s |"
            % (
                row["mol_id"],
                name,
                row.get("family", ""),
                donor_count,
                len(group),
                len(kept),
                detail or "-",
                check,
            )
        )
    lines.append("")
    lines.append(
        "Every candidate above is a row of outputs/week5/li_motif_generation.csv, "
        "including the ones that were dropped: dedup_reason records why."
    )
    path.write_text(chr(10).join(lines) + chr(10), encoding="utf-8", newline=chr(10))
    return path


def main(argv=None) -> int:
    args = parse_args(argv)
    located = toolchain.find_executable("xtb")
    if located is None:
        raise SystemExit("xtb not found; see scripts/check_environment.py")
    args.xtb_executable = str(located.path)
    version = toolchain.read_version(located.path, "xtb")

    rows = select_rows(load_core_set(), args.only, args.limit)
    started = time.perf_counter()
    records = []
    for row in rows:
        print("motif generation:", row["mol_id"], row["name"], flush=True)
        records.extend(run_molecule(row, args, args.xtb_executable))

    csv_path = write_csv(Path(args.outdir) / "li_motif_generation.csv", records)
    md_path = write_markdown(Path(args.outdir) / "li_motif_generation.md", records, rows)
    kept = [record for record in records if record["kept"]]
    summary = {
        "stage": "T4-step1-li-motif-generation",
        "rule": "config/scientific_definitions.yaml conformers_and_states.li_motif_generation",
        "xtb_version": version,
        "molecules": [row["name"] for row in rows],
        "n_candidates": len(records),
        "n_kept_motifs": len(kept),
        "n_molecules_with_motif": len({record["name"] for record in kept}),
        "energy_window_kj": args.energy_window_kj,
        "max_motifs_per_molecule": args.max_motifs,
        "esp_supplement": not args.skip_esp,
        "rule_checks": sorted({record["donor_rule_check"] for record in records}),
        "placement_counts": {
            placement: sum(1 for record in records if record["placement"] == placement)
            for placement in ("monodentate", "bidentate", "bidentate_long", "esp_min")
        },
        "qc_flag_counts": {
            flag: sum(1 for record in records if flag in (record["qc_flags"] or ""))
            for flag in (
                "geometry_failed",
                "no_intact_minimum_found",
                "motif_switch",
                "dissociated_optimized_product",
            )
        },
        "seconds": round(time.perf_counter() - started, 2),
        "command": "scripts/build_li_motifs.py " + " ".join(sys.argv[1:]),
        "csv": relative(csv_path),
        "markdown": relative(md_path),
        "motifs": [
            {
                "mol_id": record["mol_id"],
                "name": record["name"],
                "family": record["family"],
                "motif_id": record["motif_id"],
                "donors": list(record["donors"]),
                "contact_donor_indices": list(record["donor_contacts"]),
                "placement": record["placement"],
                "energy_eh": record["preopt_energy_eh"],
                "energy_rel_kj": record["preopt_energy_rel_kj"],
                "path": record["motif_path"],
                "qc_flags": record["qc_flags"],
            }
            for record in kept
        ],
    }
    json_path = Path(args.outdir) / "li_motif_generation.json"
    json_path.write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + chr(10),
        encoding="utf-8",
        newline=chr(10),
    )
    print(
        json.dumps(
            {
                "n_candidates": summary["n_candidates"],
                "n_kept_motifs": summary["n_kept_motifs"],
                "rule_checks": summary["rule_checks"],
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
